spring:
  application:
    name: AlertNews
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: sa
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    include: oauth
